services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Swisscode\Newt\Domain\Repository\:
    resource: '../Classes/Domain/Repository/*'

  Swisscode\Newt\Controller\:
    resource: '../Classes/Controller/*'
